#
# ItemFrameProtectionPlugin
#                              by ちのなみ (https://github.com/kanasaki15)
# 自分で作っといてプラグイン名なげえ・・・
#

errorPrint: true # 「false」にするとプラグイン自体にエラーが出ても見てみぬする (下記のMySQLの設定がおかしいとかバグったとか)


useMySQL: false # MySQL使うなら「true」。falseだったら何もおきない。意味がない。
MySQLServer: '' # サーバー名
MySQLUsername: '' # ユーザー名
MySQLPassword: '' # パスワード
MySQLDatabase: '' # データベース名
MySQLOption: '?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false' # オプション (MySQL 5.6以降にはデフォで書かれているのが必須らしい。)