#
# ItemFrameProtectionPlugin
#                              by ちのなみ (https://github.com/kanasaki15)
# 自分で作っといてプラグイン名なげえ・・・
#

userMessage: false # 「true」にすると額縁を設置したときに設置した人にお知らせしてくれる
errorPrint: true # 「false」にするとプラグイン自体にエラーが出ても見てみぬする (下記のMySQLの設定がおかしいとかバグったとか)

useMySQL: false # MySQL使うなら「true」。falseだったら何もおきない。意味がない。
MySQLServer: '' # サーバー名
MySQLUsername: '' # ユーザー名
MySQLPassword: '' # パスワード
MySQLDatabase: '' # データベース名
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false' # オプション (MySQL 5.6以降にはデフォで書かれているのが必須らしい。)