#
# ItemFrameProtectionPlugin
#                              by ちのなみ (https://github.com/kanasaki15)
# 自分で作っといてプラグイン名なげえ・・・
#

MySQLServer: '' # サーバー名
MySQLPort: 3306 # ポート番号
MySQLUsername: '' # ユーザー名
MySQLPassword: '' # パスワード
MySQLDatabase: '' # データベース名
MySQLOption: '?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false' # オプション (MySQL 5.6以降にはデフォで書かれているのが必須らしい。)