name: ItemFrameProtectionPlugin
version: @version@
main: xyz.n7mn.dev.yululi.itemframeprotectionplugin.ItemFrameProtectionPlugin
authors: [ n3m_ ]
description: ItemFrameProtectionPlugin
website: https://n7mn.xyz/
commands:
  ifp:
    description: '説明いる？'
    usage: '/ifp'
